### ISSUE TITLE
Broken requirements.txt

### ISSUE THREAD

**Issue by FFY00** [randaller/cnn-rtlsdr#3]
Please make the packages in `requirements.txt` compliant with the current repository versions.

It is possible to install but it's not optimal.

**Comment by randaller** [comment]
It's not so easy, as I have tons of installed libraries in my windows env and pip freeze lists them all.

There are commands for installation on:
Ubuntu: https://github.com/randaller/cnn-rtlsdr/issues/1#issuecomment-362201646
Kali: https://github.com/randaller/cnn-rtlsdr/issues/1#issuecomment-362215420

Nearly the same instructions should also work on windows. Pip install tensorflow-gpu, pip install keras and may be pip install something more, python interpreter will say which "module is not found".

**Comment by randaller** [comment]
The only really needed packages for Ubuntu:
```
tensorflow==1.5
pyrtlsdr
scipy
keras
sklearn
```
