### ISSUE TITLE
usage of dataset2.py file

### ISSUE THREAD

**Issue by sidhu037** [randaller/cnn-rtlsdr#7]
Hi,

I would like to know whether the dataset2.py and dataset.py file are used for testing the training model. Please let me know how can  I test the trained model?

**Comment by randaller** [comment]
Dataset2.py is for preparing data for keras version, while dataset.py is used by older tensorflow version.
The bottom part of train_keras.py also tests the trained model after training.

**Comment by sidhu037** [comment]
Thank you for your response
